In [1]:
import pandas as pd

In [12]:
data = pd.read_csv("Pokemon.csv")

In [4]:
data.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

## ADD COLUMS 
## Speed_High_Low

In [10]:
 speed_mean = data["Speed"].mean()
def set_speed(val):
    if val < speed_mean:
        return "Speed Low"
    elif val == speed_mean:
        return "Speed neutral"
    else:
        return "Speed High"

In [11]:
data["Speed_high_low"] = data["Speed"].apply(set_speed)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Speed Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Speed Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Speed High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Speed High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Speed Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Speed Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Speed High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Speed High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Speed High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Speed High

## ADD COLUMN
## HP_HIGH_LOW

In [13]:
data["HP"].mean()

69.25875

In [15]:
hp_mean = data["HP"].mean()
def set_mean(val):
    if val < hp_mean:
        return "Hp Low"
    elif val == hp_mean:
        return "Hp Neutral"
    else:
        return "Hp High"

In [16]:
data["Hp_High_Low"] = data["HP"].apply(set_mean)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Hp_High_Low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Hp Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Hp Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Hp High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Hp High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Hp Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Hp Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Hp Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Hp High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Hp High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Hp High